<?php

namespace MyFrameWork\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-25 at 08:16:17.
 */
class RemoveAccentTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RemoveAccent
     */
    protected $remover;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->remover = new RemoveAccent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MyFrameWork\Common\RemoveAccent::filter
     * @todo   Implement testFilter().
     */
    public function testFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
