<?php
require_once 'util/datatype/DatatypeEmail.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-07-19 at 10:02:16.
 */
class DatatypeEmailTest extends DatatypeBaseTest {

    /**
     * @var DatatypeEmail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->object = new DatatypeEmail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testSanitize() {
        $this->assertEquals($this->data['email'], $this->object->sanitize($this->data['email']));
        
        //Não é válido mas poderia ser um email
        $this->assertEquals('joao.souza@teste.com.br.edu.mu', $this->object->sanitize('joao.souza@teste.com.br.edu.mu'));
        $this->assertEquals('wwww.joao.souza@teste.com.br.edu.mu', $this->object->sanitize('wwww.joao.souza@teste.com.br.edu.mu'));
        
        //Invalidos
        $this->assertNull($this->object->sanitize($this->data['invalidemail']));
        $this->assertNull($this->object->sanitize($this->data['str']));
        $this->assertNull($this->object->sanitize('http://www.uol.com.br'));
    }
    
    public function testIsValid() {
        $this->assertTrue($this->object->isValid($this->data['email']));
        $this->assertTrue($this->object->isValid('joao.souza@teste.com.br.edu.mu'));
        $this->assertTrue($this->object->isValid('wwww.joao.souza@teste.com.br.edu.mu'));
        $this->assertFalse($this->object->isValid($this->data['invalidemail']));
        $this->assertFalse($this->object->isValid($this->data['str']));
        $this->assertFalse($this->object->isValid('http://www.uol.com.br'));
        
        $params = array(Flag::VALIDATE_DOMAIN);
        $this->assertFalse($this->object->isValid('joao.souza@teste.com.br.edu.mu', $params));
        $this->assertFalse($this->object->isValid('wwww.joao.souza@teste.com.br.edu.mu', $params));
        //$this->assertTrue($this->object->isValid('teste.teste@uol.com.br', $params));
    }

}
